[theme]
primaryColor = "#F56400"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262626"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
